const resumeData = {
  name: 'Francis P. Craven',
  email: 'craven.francis@gmail.com',
  github: 'https://www.github.com/FCraven',
  linkedin: 'https://www.linkedin.com/in/francis-craven-ab1029b3',
  summary:
    'Front-end engineer and computer science student focused on performant, design-forward experiences. I blend commerce, component systems, and developer experience work to ship reliable products and lead teams well.',
  education: [
    {
      institution: 'CUNY Queens College',
      degree: 'B.S. Computer Science',
      start_date: 'Sep 2023',
      end_date: 'Present',
    },
    {
      institution: 'Fullstack Academy',
      degree: 'Certificate',
      start_date: 'Jun 2018',
      end_date: 'Oct 2018',
    },
  ],
  experience: [
    {
      company: 'Digital Fuel Capital',
      role: 'Front End Engineer',
      start_date: 'Apr 2022',
      end_date: 'Jul 2023',
      techStack: [
        { name: "Shopify", icon: "SiShopify", },
        { name: "React.js", icon: "SiReact", },
        { name: "Node.js", icon: "SiNodedotjs", },
        { name: "Webpack", icon: "SiWebpack", },
        { name: "Gulp", icon: "SiGulp", },
        { name: "Grunt", icon: "SiGrunt",},
        { name: "Git", icon: "SiGit", },
        { name: "Google Analytics", icon: "SiGoogleanalytics", },
      ],
      projects: [
        {
          name: 'Boutique Brands',
          image: '/dfc/logo_the_boutique_brands.png',
          link: "https://digitalfuelcapital.com/portfolio-boutique-brands"
        },
        {
          name: "LimeLush",
          image: "/dfc/logo_lime_lush.png",
          link: "https://www.limelush.com",
        },
        {
          name: "Filly Flair",
          image: "/dfc/logo_filly_flair.png",
          link: "https://www.fillyflair.com",
        },
        {
          name: "Nana Macs",
          image: "/dfc/logo_nana_macs.png",
          link:"https://www.nanamacs.com",
        },
        {
          name: "Discount Divas",
          image: "/dfc/logo_discount_divas.png",
          link: "https://www.discountdivas.com",
        },
      ],
      achievements: [
        'Led technical enhancements across four women’s eCommerce platforms, influencing a monthly revenue increase to $1.5M through strategic optimizations & innovations.',
        'Spearheaded integration of Shopify’s React.js Hydrogen for headless commerce, enhancing storefront development speed & improving developer experience.',
        'Implemented site efficiency improvements increasing Lighthouse score from 3 to 55 for Lime Lush, lowering bounce rate by 12%.',
        'Retooled shell scripts, asset management & module bundling, enhancing build pipeline efficiency.',
        'Boosted development team productivity by implementing git flow, optimizing version control & collaboration processes.',
        'Executed comprehensive SEO remediation across all brand websites, enhancing online visibility, search engine presence & user engagement.',
      ],
      image: "/dfc/logo_dfc.jpg",
    },
    {
      company: 'Smile Direct Club',
      role: 'Front End Developer',
      start_date: 'Aug 2021',
      end_date: 'Mar 2022',
      techStack: [
        { name: "Nuxt.js", icon: "SiNuxtdotjs", },
        { name: "Vue.js", icon: "SiVuedotjs", },
        { name: "Vuetify", icon: "SiVuetify", },
        { name:"Contentful CMS", icon: "SiContentful", },
        { name: "Storybook.js", icon: "SiStorybook", },
        { name: "Google Maps", icon: "SiGooglemaps", },
        { name: "Node.js", icon: "SiNodedotjs", }
      ],
      projects: [
        {
          name: "Brick & Morty Locator",
          image: '/sdc/brick_morty.png',
          link: null,
        }
      ],
      achievements: [
        'Developed dynamic user-facing feature Brick & Mortar Locator leveraging Vue.js, Nuxt.js, Contentful CMS, Storybook, Google Maps, Vuetify, & SDC’s component library.',
        'Worked closely with UX designers to match end product with technical specifications.',
        'Collaborated with backend team to develop data models & REST APIs.',
        'Authored documentation for projects ensuring clarity & accessibility for cross-team reference & future maintenance.',
      ],
      image: "/sdc/logo_sdc.png",
    },
    {
      company: '2U | edX',
      role: 'Web Development Educator',
      start_date: 'Mar 2019',
      end_date: 'Aug 2021',
      techStack: [
        { name: "HTML5", icon: "SiHtml5", },
        { name: "CSS3", icon: "SiCss3", },
        { name: "JavaScript", icon: "SiJavascript", },
        { name: "React.js", icon: "SiReact", },
        { name: "React Router", icon: "SiReactrouter", },
        { name: "Redux.js", icon: "SiRedux", },
        { name: "Node.js", icon: "SiNodedotjs", },
        { name: "Express.js", icon: "SiExpress", },
        { name: "MongoDB", icon: "SiMongodb", },
        { name: "SQLite", icon: "SiSqlite", },
        { name: "MySQL", icon: "SiMysql", },
        { name: "PostgresQL", icon: "SiPostgresql", },
        { name: "AWS", icon: "SiAmazonwebservices", }
      ],
      projects: [],
      achievements: [
        'Developed & delivered full stack JavaScript curriculum covering core language, front-end/back-end frameworks, databases, deployment.',
        'Conducted lectures, coding workshops, assessments focused on real-world applications.',
        'Mentored students in debugging, code reviews, & capstone projects, enhancing learning outcomes.',
        'Ran workshops on version control, API integration, & advanced topics, enriching the curriculum.',
        'Worked with coordinators to update the curriculum regularly, aligning with industry trends.',
      ],
      image: "/edX/logo_2U_edX.jpg",
    },
  ],
  skills: {
    languages: ['JavaScript', 'TypeScript', 'HTML5', 'CSS3', 'C++', 'Java', 'SQL'],
    'Front End': ['React.js', 'Redux', 'React Native', 'Vue.js', 'Next.js', 'Nuxt.js', 'jQuery'],
    ui: ['Bootstrap', 'Tailwind', 'MaterialUI', 'styled-components'],
    backEnd: [
      'Node.js',
      'ExpressJS',
      'GraphQL',
      'MongoDB',
      'MySQL',
      'PostgreSQL',
      'Heroku',
      'REST API',
    ],
    tools: [
      'AWS',
      'GCP',
      'Heroku',
      'NPM',
      'Babel',
      'Webpack',
      'Gulp',
      'Grunt',
      'Git',
      'GitHub',
      'Postman',
      'CLI',
      'Visual Studio Code',
      'Jira',
      'Figma',
      'Confluence',
      'Storybook',
      'Agile',
      'Scrum',
      'SDLC',
      'Shopify',
    ],
    testing: ['Jest', 'JSDOM', 'Chai', 'Mocha', 'Vitest', 'Enzyme', '@testing-library', 'Jasmine'],
  },
};

export default resumeData;
