const resumeData = {
  name: 'Francis P. Craven',
  handle: 'fcraven',
  email: 'craven.francis@gmail.com',
  github: 'https://www.github.com/FCraven',
  linkedin: 'https://www.linkedin.com/in/francis-craven-ab1029b3',
  tagline: 'Front-end systems architect',
  bio: 'I build commerce platforms that move real money, teach developers who ship real products, and obsess over the 200ms that separate a good interface from a great one.',
  status: 'Exploring front-end roles and consulting engagements where craft matters.',
  education: [
    {
      institution: 'CUNY Queens College',
      degree: 'B.S. Computer Science',
      start_date: 'Sep 2023',
      end_date: 'Present',
    },
    {
      institution: 'Fullstack Academy',
      degree: 'Software Engineering Immersive',
      start_date: 'Jun 2018',
      end_date: 'Oct 2018',
    },
  ],
  experience: [
    {
      company: 'SeaRaven Studios',
      codename: 'OPERATION: AGENCY BUILD',
      role: 'Founder & Lead Engineer',
      start_date: 'Jan 2026',
      end_date: 'Present',
      brief: 'Building the agency from scratch. Full-service web development studio for businesses that need more than a template. Every client site is a custom build.',
      techStack: [
        { name: "Next.js", icon: "SiNextdotjs" },
        { name: "React.js", icon: "SiReact" },
        { name: "Tailwind", icon: "SiTailwindcss" },
        { name: "Vercel", icon: "SiVercel" },
        { name: "Figma", icon: "SiFigma" },
        { name: "Node.js", icon: "SiNodedotjs" },
        { name: "Stripe", icon: "SiStripe" },
      ],
      projects: [],
      impact: [
        'Designed and built the agency itself — brand, site, infrastructure, pipeline',
        'Developing client acquisition strategy: $5K–$25K per project',
        'Building portfolio of revenue-generating web properties under SeaRaven Group',
        'Every project ships on Vercel with CI/CD from day one',
      ],
      image: null,
    },
    {
      company: 'Total Hemp',
      codename: 'OPERATION: GREEN MARKET',
      role: 'Full Stack Engineer',
      start_date: 'Dec 2025',
      end_date: 'Present',
      brief: 'Production-grade hemp/CBD e-commerce platform. Medusa backend, Next.js storefront, loyalty program, CRM, compliance engine, and fulfillment integration. The whole stack.',
      techStack: [
        { name: "Medusa.js", icon: "SiNodedotjs" },
        { name: "Next.js", icon: "SiNextdotjs" },
        { name: "React.js", icon: "SiReact" },
        { name: "PostgreSQL", icon: "SiPostgresql" },
        { name: "Tailwind", icon: "SiTailwindcss" },
        { name: "Stripe", icon: "SiStripe" },
        { name: "Node.js", icon: "SiNodedotjs" },
        { name: "Docker", icon: "SiDocker" },
      ],
      projects: [],
      impact: [
        'Architected full e-commerce platform from zero — Medusa backend + Next.js storefront',
        'Built custom loyalty/rewards system with points, tiers, and referral tracking',
        'Integrated age verification and compliance workflows for regulated products',
        'Designed CRM module for customer segmentation and lifecycle marketing',
        'ShipStation fulfillment integration for automated order processing',
        'Production PostgreSQL with custom data models for hemp-specific taxonomy',
      ],
      image: null,
    },
    {
      company: 'Digital Fuel Capital',
      codename: 'OPERATION: COMMERCE ENGINE',
      role: 'Front End Engineer',
      start_date: 'Apr 2022',
      end_date: 'Jul 2023',
      brief: 'Four women\'s fashion eCommerce brands. One engineer. $1.5M/month in combined revenue flowing through interfaces I built and optimized.',
      techStack: [
        { name: "Shopify", icon: "SiShopify" },
        { name: "React.js", icon: "SiReact" },
        { name: "Node.js", icon: "SiNodedotjs" },
        { name: "Webpack", icon: "SiWebpack" },
        { name: "Gulp", icon: "SiGulp" },
        { name: "Grunt", icon: "SiGrunt" },
        { name: "Git", icon: "SiGit" },
        { name: "Google Analytics", icon: "SiGoogleanalytics" },
      ],
      projects: [
        { name: 'Boutique Brands', image: '/dfc/logo_the_boutique_brands.png', link: "https://digitalfuelcapital.com/portfolio-boutique-brands" },
        { name: "LimeLush", image: "/dfc/logo_lime_lush.png", link: "https://www.limelush.com" },
        { name: "Filly Flair", image: "/dfc/logo_filly_flair.png", link: "https://www.fillyflair.com" },
        { name: "Nana Macs", image: "/dfc/logo_nana_macs.png", link: "https://www.nanamacs.com" },
        { name: "Discount Divas", image: "/dfc/logo_discount_divas.png", link: "https://www.discountdivas.com" },
      ],
      impact: [
        '$1.5M/month revenue influenced across four commerce platforms',
        'Lighthouse score: 3 → 55 on LimeLush. Bounce rate dropped 12%.',
        'Spearheaded Shopify Hydrogen integration for headless commerce',
        'Rebuilt build pipelines — shell scripts, asset management, module bundling',
        'Implemented git flow across the team. Velocity up. Bugs down.',
        'Full SEO remediation across all brand properties',
      ],
      image: "/dfc/logo_dfc.jpg",
    },
    {
      company: 'Smile Direct Club',
      codename: 'OPERATION: BRICK & MORTAR',
      role: 'Front End Developer',
      start_date: 'Aug 2021',
      end_date: 'Mar 2022',
      brief: 'Built the store locator that helped customers find their nearest SmileShop. Vue.js, Google Maps, and a lot of edge cases.',
      techStack: [
        { name: "Nuxt.js", icon: "SiNuxtdotjs" },
        { name: "Vue.js", icon: "SiVuedotjs" },
        { name: "Vuetify", icon: "SiVuetify" },
        { name: "Contentful CMS", icon: "SiContentful" },
        { name: "Storybook.js", icon: "SiStorybook" },
        { name: "Google Maps", icon: "SiGooglemaps" },
        { name: "Node.js", icon: "SiNodedotjs" },
      ],
      projects: [
        { name: "Brick & Mortar Locator", image: '/sdc/brick_morty.png', link: null },
      ],
      impact: [
        'Built the Brick & Mortar Locator from scratch — Vue.js, Nuxt, Google Maps, Contentful',
        'Paired with UX designers to nail the interaction design',
        'Collaborated with backend team on data models and REST APIs',
        'Wrote the docs that made the next developer\'s life easier',
      ],
      image: "/sdc/logo_sdc.png",
    },
    {
      company: '2U | edX',
      codename: 'OPERATION: KNOWLEDGE TRANSFER',
      role: 'Web Development Educator',
      start_date: 'Mar 2019',
      end_date: 'Aug 2021',
      brief: '350+ developers taught full-stack JavaScript. From "what is a variable?" to deploying production apps on AWS.',
      techStack: [
        { name: "HTML5", icon: "SiHtml5" },
        { name: "CSS3", icon: "SiCss3" },
        { name: "JavaScript", icon: "SiJavascript" },
        { name: "React.js", icon: "SiReact" },
        { name: "React Router", icon: "SiReactrouter" },
        { name: "Redux.js", icon: "SiRedux" },
        { name: "Node.js", icon: "SiNodedotjs" },
        { name: "Express.js", icon: "SiExpress" },
        { name: "MongoDB", icon: "SiMongodb" },
        { name: "SQLite", icon: "SiSqlite" },
        { name: "MySQL", icon: "SiMysql" },
        { name: "PostgresQL", icon: "SiPostgresql" },
        { name: "AWS", icon: "SiAmazonwebservices" },
      ],
      projects: [],
      impact: [
        '350+ developers trained from zero to full-stack',
        'Built and delivered curriculum: HTML → CSS → JS → React → Node → Databases → AWS',
        'Led live coding workshops, debugging sessions, and capstone reviews',
        'Created supplemental workshops on version control and API integration',
        'Continuously updated curriculum to match industry movement',
      ],
      image: "/edX/logo_2U_edX.jpg",
    },
  ],
  skills: {
    languages: ['JavaScript', 'TypeScript', 'HTML5', 'CSS3', 'C++', 'Java', 'SQL'],
    frontend: ['React.js', 'Redux', 'React Native', 'Vue.js', 'Next.js', 'Nuxt.js'],
    ui: ['Tailwind', 'Bootstrap', 'MaterialUI', 'styled-components'],
    backend: ['Node.js', 'Express', 'GraphQL', 'MongoDB', 'MySQL', 'PostgreSQL', 'Medusa.js', 'REST API'],
    tooling: ['AWS', 'GCP', 'Docker', 'Webpack', 'Gulp', 'Git', 'Postman', 'Figma', 'Jira', 'Storybook', 'Shopify', 'Vercel'],
    testing: ['Jest', 'Vitest', 'Chai', 'Mocha', 'Enzyme', '@testing-library', 'Jasmine'],
  },
};

export default resumeData;
