import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiExpress,
  SiReactrouter,
  SiRedux,
  SiMongodb,
  SiSqlite,
  SiMysql,
  SiPostgresql,
  SiAmazonwebservices,
  SiReact,
  SiShopify,
  SiWebpack,
  SiGit,
  SiGulp,
  SiGrunt,
  SiNodedotjs,
  SiGoogleanalytics,
  SiVuedotjs,
  SiVuetify,
  SiNuxtdotjs,
  SiContentful,
  SiStorybook,
  SiGooglemaps,
} from 'react-icons/si';

const iconMapping = {
  SiHtml5: SiHtml5,
  SiCss3: SiCss3,
  SiJavascript: SiJavascript,
  SiExpress: SiExpress,
  SiReactrouter: SiReactrouter,
  SiRedux: SiRedux,
  SiMongodb: SiMongodb,
  SiSqlite: SiSqlite,
  SiMysql: SiMysql,
  SiPostgresql: SiPostgresql,
  SiAmazonwebservices: SiAmazonwebservices,
  SiReact: SiReact,
  SiShopify: SiShopify,
  SiWebpack: SiWebpack,
  SiGit: SiGit,
  SiGulp: SiGulp,
  SiGrunt: SiGrunt,
  SiNodedotjs: SiNodedotjs,
  SiGoogleanalytics: SiGoogleanalytics,
  SiVuedotjs: SiVuedotjs,
  SiVuetify: SiVuetify,
  SiNuxtdotjs: SiNuxtdotjs,
  SiContentful: SiContentful,
  SiStorybook: SiStorybook,
  SiGooglemaps: SiGooglemaps,
}

export default iconMapping;
